### PR TITLE
Update Scoring Algorithm

### PR DESCRIPTION
**Pull request by zednis**
Update scoring scoring to use new algorithm developed by @anirudhprabhu 

links: [scoring algorithm documentation](/blob/master/doc/Scoring%20Algorithm/DarkData.pdf)

### CODE REVIEW

**Comment by zednis** [comment]
@anirudhprabhu I believe the new scoring algorithm has been successfully implemented.  Can you review the changes and verify?

**Comment by anirudhprabhu** [comment]
Can you explain what the following functions do?

```
    private String getCompatibilityValueIdentifier(Model m, Resource compatibilityValue) {
        return m.listObjectsOfProperty(compatibilityValue, DCTerms.identifier)
                .toList().stream()
                .map(RDFNode::asLiteral)
                .map(Literal::getString)
                .findAny().orElse("DEFAULT");
    }

    private List<Resource> getCompatibilityAssertionsForCandidate(Model m, Resource candidate) {
        return m.listObjectsOfProperty(candidate, DarkData.compatibilityAssertion)
                .toList().stream()
                .map(RDFNode::asResource)
                .collect(Collectors.toList());
    }
}

```

**Comment by anirudhprabhu** [comment]
Can you also give me an example of the kind of values that an object of type ``` DoubleSummaryStatistics ``` may hold?

For instance, 
Here
```
private DoubleSummaryStatistics summarizeConfidence(Model m, List<Resource> assertions) {
        return assertions.stream()
                .map(a -> getConfidence(m, a))
                .collect(Collectors.summarizingDouble(a -> a));
    }
```

and Here,
```
protected Double computeRawScoreForCompatibilityValue(Model m, Map.Entry<Resource, DoubleSummaryStatistics> e, Double naMax) {
        DoubleSummaryStatistics confidenceStats = e.getValue();
        double numAssertions = confidenceStats.getCount();
        double maxConfidence = confidenceStats.getMax();
        double sumConfidence = confidenceStats.getSum();
        double weight = getWeight(m, e.getKey());
        return (sumConfidence / maxConfidence * weight) * (numAssertions / naMax);
    }
```

**Comment by anirudhprabhu** [comment]
Another thing I noticed is that the max confidence value being used is not the maximum value for a candidate, but for an assertion.

For example, in SimpleScoringTest.java, in ```testScore() ```
Instead of, 
```double expected = Math.log10(
                ((2d / 1d * SOME_WEIGHT) * (3d / 3d))
                        + ((0.5d / 0.5d * SLIGHT_WEIGHT) * (1d / 3d))
        );```

It should be 
```double expected = Math.log10(
                ((2d / 1d * SOME_WEIGHT) * (3d / 3d))
                        + ((0.5d / 1d * SLIGHT_WEIGHT) * (1d / 3d))
        );```

**Comment by zednis** [comment]
DoubleSummaryStatistics documentation: https://docs.oracle.com/javase/8/docs/api/java/util/DoubleSummaryStatistics.html

>A state object for collecting statistics such as count, min, max, sum, and average.
This class is designed to work with (though does not require) streams.

In this case the summary statistics object contains information about the confidence values for a given compatibility value (STRONG, SLIGHT, SOME, etc) associated with the current candidate.

**Comment by zednis** [comment]
Good catch on the maxConfidence value, I will update the code.

**Comment by zednis** [comment]
SimpleScoringService::getCompatibilityValueIdentifier returns a string value for the ``dcterms:identifier`` value of a CompatibilityValue resource, example values are "STRONG", "SLIGHT", "SOME", etc.  These are then matched against properties in simpleWeights.properties to get the weight value (numeric).

This is overlap with CompatibilityValue::getIdentifier method, but creating a CompatibilityValue object requires us to pass a OntResource into the constructor (and use an OntModel), so I will add a new static method that works with just Resources and Models. 

SimpleScoringService::getCompatibilityAssertionsForCandidate returns a list of resources that are compatibility assertions for a given candidate workflow.  This should get moved to CompatibilityAssertionRepository - so I will do so in the next commit.

**Comment by anirudhprabhu** [comment]
:shipit:

**Pull request merged**
